Intake
frc-7419/Offseason2025Beta pull request #10
Opened 2024-11-22 06:01 UTC by CryptoSOL123

The intake subsystem is fully ready to be merged into the master.
**Pending checks from software leads.**
![Screenshot 2024-11-21 220058](https://github.com/user-attachments/assets/24bf3982-5983-4803-b399-872ddc571bef)

2024-11-22 06:05 UTC, MostOriginalIGN commented on src/main/java/frc/robot/Commands/RunIntakeWithController.java
> +    if ((joystick.rightBumper().getAsBoolean() || joystick.leftBumper().getAsBoolean())); // Need to check if it return True when pressed or vice versa
This semicolon on the if prematurely ends the statement so the setPower is not included in the statement and will always run.

2024-11-22 06:10 UTC, MostOriginalIGN requested changes
There are some small issues left in the code but otherwise everything seems good. Keep in mind to put any variable declaration for subsystems and controllers as private final. It's missing in some files.

2024-11-22 06:10 UTC, MostOriginalIGN commented on src/main/java/frc/robot/Commands/RunIntakeWithController.java
> +    if ((joystick.rightBumper().getAsBoolean() || joystick.leftBumper().getAsBoolean())); // Need to check if it return True when pressed or vice versa
This semicolon on the if prematurely ends the statement so the setPower is not included in the statement and will always run.

2024-11-22 06:10 UTC, MostOriginalIGN commented on src/main/java/frc/robot/Commands/RunIntakeWithController.java
> +    if (beamBreakSubsystem.frontBeamBreakIsTriggered() == true || beamBreakSubsystem.backBeamBreakIsTriggered() == true) {
== true is repetitive
true is always equal to true

2024-11-22 06:10 UTC, MostOriginalIGN commented on src/main/java/frc/robot/Commands/RunVelocity.java
> +  PIDController pidController = new PIDController(IntakeConstants.kP, IntakeConstants.kI, IntakeConstants.kD);
Should have been initialized in initalize instead as a final but it's okay.

2024-11-22 06:22 UTC, Jolteous requested changes
The error in your build is due to a naming conflict in your Java classes. The logs indicate that there are multiple issues related to the Constants class and the IntakeConstants class. Here are the key points from the logs:

Package and Class Naming Conflict:

package frc.robot.Constants; clashes with class Constants.
class Constants clashes with the package of the same name.
Symbol Not Found Errors:

The class IntakeConstants cannot be found in multiple files (IntakeSubsystem.java, BeamBreakSubsystem.java, RunVelocity.java).
Steps to Fix the Errors
Rename the Constants Class:

Rename the Constants class to avoid conflict with the frc.robot.Constants package. For example, you can rename it to RobotConstants.
Correct the Imports:

Ensure that the imports in your classes refer to the correct package and class names. For example:
import frc.robot.RobotConstants.IntakeConstants;
Update the Class Declarations:

Update the class declarations to match the new class names. For example:
public class RobotConstants {
    public static class IntakeConstants {
        // Define the constants here
    }
}


While you may be able to build on WPILIB it's best that you fix these to reduce issues in the future.

2024-11-22 17:46 UTC, flashrun24 commented on src/main/java/frc/robot/Subsystems/IntakeSubsystem.java
> +  private final SparkMax motorTwo;
Please give more relevant variable names such as topMotor and bottomMotor.

2024-11-22 17:49 UTC, flashrun24 commented on src/main/java/frc/robot/Constants/IntakeConstants.java
> +    public static final MotorType motorTwoType = MotorType.kBrushless;
You shouldn't make the motor type a constant since we basically always use brushless and you only use the constant once so at this point its just repeating yourself for no reason.

2024-11-22 17:54 UTC, flashrun24 commented on src/main/java/frc/robot/Subsystems/IntakeSubsystem.java
> +  }
Make a get velocity method for the top and bottom motors as the velocities may be different

2024-12-02 07:22 UTC, flashrun24 approved these changes
I think this is good to merge now that those problem have been fixed

2024-12-02 18:13 UTC, MostOriginalIGN approved these changes
Everything looks good other than some naming issues.

2024-12-02 18:13 UTC, MostOriginalIGN commented on src/main/java/frc/robot/Constants/IntakeConstants.java
> +    public static final int backBeamBrake = 7;
break

2024-12-02 18:13 UTC, MostOriginalIGN commented on src/main/java/frc/robot/Subsystems/BeamBreakSubsystem.java
> +      SmartDashboard.putBoolean("Back Beam Brake Triggered", backBeamBreakIsTriggered());
break and brake

2024-12-03 19:01 UTC, pranshu-khanna commented
The folder names for "Commands", "Constants", and "Subsystems" should all be lowercase to resolve import errors. If I change these on Github, the changes do not reflect, so you all will have to change these on your local level.

2024-12-09 17:42 UTC, Jolteous approved these changes
@CryptoSOL123 Merge this yourself

2024-12-09 20:16 UTC, merged