Intake
frc-7419/Offseason2025Beta pull request #8
Opened 2024-11-20 00:27 UTC by Eshan41

Made by Pradyun Pranshu Eshan Ahana

2024-11-20 00:51 UTC, Jolteous approved these changes
Good job, could use some updates, but for now let's merge this.

2024-11-20 00:56 UTC, MostOriginalIGN approved these changes
Looks great other than a small warning and some naming conventions.

2024-11-20 00:56 UTC, MostOriginalIGN commented on src/main/java/frc/robot/Commands/RunVelocity.java
> +  PIDController pidController = new PIDController(IntakeConstants.kP, IntakeConstants.kI, IntakeConstants.kD);
Should have been initalized in initalize instead but will not cause any immediate issues.

2024-11-20 22:03 UTC, flashrun24 commented
You forgot a semicolon, 
![image](https://github.com/user-attachments/assets/2026c5d3-a7ac-435f-995d-b3c21534850e)

2024-11-21 08:11 UTC, Jolteous requested changes
You're missing a semicolon. Check that the project builds before making a commit.

2024-11-21 08:32 UTC, MostOriginalIGN requested changes
Several breaking issues in this code. Please make sure you check your code for errors and verify that it builds.

2024-11-21 08:32 UTC, MostOriginalIGN commented on src/main/java/frc/robot/Commands/RunIntakeWithController.java
> +  public RunIntakeWithController( CommandXboxController joystick) {
Bad constructor. Requires intakeSubsystem but is not passed in.
```suggestion
  public RunIntakeWithController( CommandXboxController joystick, IntakeSubsystem intakeSubsystem) {
```

2024-11-21 08:32 UTC, MostOriginalIGN commented on src/main/java/frc/robot/Commands/RunIntakeWithController.java
> +    if ((joystick.getRightBumperPressed || joystick.getLeftBumperPressed()));
getRightBumperPressed needs to be called as a function
```suggestion
    if ((joystick.getRightBumperPressed() || joystick.getLeftBumperPressed()));
```

2024-11-21 08:32 UTC, MostOriginalIGN commented on src/main/java/frc/robot/Commands/RunIntakeWithController.java
> +      intakeSubsystem.setPower(0.9)
missing ;
```suggestion
      intakeSubsystem.setPower(0.9);
```

2024-11-22 05:46 UTC, CryptoSOL123 commented
My team made these changes after the pull request. Do the changes show on the master branch after we push to it? I didn't have time to fix the errors that were made after the pull request since more stuff was added.

2024-11-22 05:46 UTC, closed without merging

2024-11-22 05:50 UTC, MostOriginalIGN commented
No, changes do not show on the master branch after you push to it. After a pull request is created, it captures the changes made up to that point, and additional changes will only show in the PR if they are pushed to the same branch associated with it. If your team made changes after the PR and pushed them, they should appear in the PR if they were committed to the correct branch; however, they won’t show in the master branch unless the PR has been merged into master and the branch is updated both locally and remotely. 

This PR did not need to be closed and you can make the necessary changes. Or create a new pull request when you are ready.