Finished drivetrain
frc-7419/Offseason2025Beta pull request #9
Opened 2024-11-20 19:42 UTC by mqxs21

I made the drivetrain code manually since i had to wait to long to generate it, also set up pathplanner autochooser and drivetrain in robotcontainer.

2024-11-20 21:59 UTC, flashrun24 commented
Can you please explain why you have so many weird vendor deps such as DogLog, Studica, URCL, and two pathplanners

2024-11-21 02:34 UTC, Jolteous approved these changes
While this isn't exactly like the conventional way we do swerve drive, it is usable. You may run into some issues with driving that can be worked out later, but generally this seems good. Reminds me of @flashrun24's code from 2023.

2024-11-21 02:37 UTC, Amrit-s-RIS commented
> Can you please explain why you have so many weird vendor deps such as DogLog, Studica, URCL, and two pathplanners @Amrit-s-RIS

I downloaded all the vendor dependencies I could from the WPILib menu in case i would need to use them while coding. I didn't think there would be anything wrong with this, does it cause issues with the rest of the code?

2024-11-21 05:20 UTC, wlmchen requested changes

2024-11-21 05:20 UTC, wlmchen commented on src/main/java/frc/robot/subsystems/SwerveBase.java
> +    return ChassisSpeeds.fromFieldRelativeSpeeds(vx, vy, rx, gyro.getRotation2d());
`.4` as a deadband is quite a lot, you'd have to move the joystick almost halfway to get any movement. Usually we go with something lower. Deadband is only really necessary if the controller drifts, i.e has tiny readings (usually under `.1`) without being touched

2024-11-21 05:23 UTC, wlmchen commented
> > Can you please explain why you have so many weird vendor deps such as DogLog, Studica, URCL, and two pathplanners @Amrit-s-RIS
> 
> I downloaded all the vendor dependencies I could from the WPILib menu in case i would need to use them while coding. I didn't think there would be anything wrong with this, does it cause issues with the rest of the code?

If we aren't using it, it just adds initial build+fetch time and overhead(?), doesn't affect the code but still best to remove it. There's also [Namespace Pollution](https://stackoverflow.com/questions/29707809/does-namespace-pollution-in-java-or-c-sharp-exist-like-in-c) if you're curious.

2024-11-21 05:44 UTC, MostOriginalIGN requested changes
Looks great so far other than the two Pathplanners in vendordeps and the other random libraries. This should be cleaned to prevent overhead and I believe the two pathplanners may cause conflicts as the share the same package names.

Also, you could look at [CTRE's examples repo](https://github.com/CrossTheRoadElec/Phoenix6-Examples/tree/main/java/SwerveWithPathPlanner) where they have the generated swerve code already.  All you would need to do later is to generate TunerConstants. There no shame in copy pasting the CommandSwerveDrivetrain code as it's already generated anyways.

2024-11-21 05:46 UTC, flashrun24 requested changes
I don't have anything to add, just make the changes mentioned by William and win

2024-11-21 05:59 UTC, mqxs21 commented
i made the changes and cleaned up the vendordeps

2024-11-21 06:04 UTC, flashrun24 approved these changes
Although there is more to be done I think that this is good to merge for now :)

2024-11-21 06:13 UTC, wlmchen approved these changes

2024-11-21 06:22 UTC, MostOriginalIGN approved these changes

2024-11-21 08:09 UTC, Jolteous commented
Go ahead and merge @mqxs21

2024-11-21 08:15 UTC, merged